import Home from './Home/Home';
import Root from './root';
import ErrorPage from './ErrorPage';
import Temple from './Temple/Temple';
import Reception from './Reception/Reception';
import Schedule from './Schedule/Schedule';
import Photos from './Photos/Photos';
import Registry from './Registry/Registry';
import RSVP from './RSVP/RSVP';
export { Home, Root, ErrorPage, Temple, Reception, Schedule, Photos, Registry, RSVP };
